springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8080}

spring:
  application:
    name: petstorepetservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: "jdbc:postgresql://msajd-petstore.postgres.database.azure.com:5432/petstore?currentSchema=petstorepetservice_db"
    username: "msajd"
    password: "paSSw0rd"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true
