springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8080}

spring:
  application:
    name: petstorepetservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${dbPetServiceUrl}
    username: ${dbUser}
    password: ${dbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://msajdkv.vault.azure.net/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true
